"""Android host: UISpec -> a Jetpack Compose application.

One detail in this renderer carries disproportionate weight for the paper's
accessibility results. Compose associates an accessible name with a text field
only when the composable receives a `label` (or an explicit
`semantics { contentDescription = ... }`). A neighbouring `Text` composable that
looks like a label to a sighted user associates with nothing. Renderers that
overlook this emit fields that are visually labelled and programmatically
anonymous -- the exact defect the Android accessibility literature reports at
scale in LLM-generated UI.

This renderer sets the label explicitly. The host profile records that Compose
does not derive names implicitly, so a condition-A generation that omits it will
show up as an accessibility-parity gap rather than passing silently.
"""

from __future__ import annotations

import json

from .base import COMPOSE
from .bridge import DEFAULT_PORTS, HttpBridgeSession
from .session import SimulatedSession

APP_KT = '''// Generated by HostShift. Do not edit; regenerate from the spec.
package dev.hostshift.generated

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.testTag
import androidx.compose.ui.unit.dp
import org.json.JSONObject

private const val SPEC_JSON = """{spec_json}"""

val SPEC: JSONObject = JSONObject(SPEC_JSON)

// Runtime state. Mirrors hostshift/render/semantics.py as an independent
// implementation; the divergence between platform runtimes is the measurement.
class SpecState {{{{
    val values = mutableStateMapOf<String, Any?>()
    val collections = mutableStateMapOf<String, MutableList<MutableMap<String, Any?>>>()
    var route by mutableStateOf(SPEC.optString("entry"))

    init {{{{ reset() }}}}

    fun reset() {{{{
        values.clear(); collections.clear()
        SPEC.optJSONObject("state")?.let {{{{ decls ->
            decls.keys().forEach {{{{ k ->
                val d = decls.getJSONObject(k)
                values[k] = if (d.has("default")) d.get("default") else when (d.optString("type")) {{{{
                    "string" -> ""; "number" -> 0; "boolean" -> false; else -> null
                }}}}
            }}}}
        }}}}
                values[k] = if (d.has("default")) d.get("default") else when (d.optString("type")) {{
                    "string" -> ""; "number" -> 0; "boolean" -> false; else -> null
                }}
            }}
        }}
        SPEC.optJSONObject("collections")?.let {{ colls ->
            colls.keys().forEach {{ k -> collections[k] = mutableListOf() }}
        }}
        route = SPEC.optString("entry")
    }}

    fun resolve(path: String?): Any? {{
        if (path == null) return null
        if (path.endsWith(".length")) {{
            val base = resolve(path.substring(0, path.length - 7))
            return when (base) {{
                is Collection<*> -> base.size
                is String -> base.length
                is JSONArray -> base.length()
                is JSONObject -> base.length()
                else -> null
            }}
        }}
        val parts = path.split(".")
        var cur: Any? = values[parts[0]] ?: collections[parts[0]] ?: values
        for (i in (if (cur === values || cur === collections) 0 else 1) until parts.size) {{
            val p = parts[i]
            cur = when (cur) {{
                is Map<*, *> -> cur[p]
                is JSONObject -> cur.opt(p)
                else -> null
            }}
            if (cur == null) break
        }}
        return cur
    }}
}}

@Composable
fun SpecNodes(nodes: List<JSONObject>, state: SpecState) {{
    Column(
        modifier = Modifier.padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {{ nodes.forEach {{ SpecNode(it, state) }} }}
}}

@Composable
fun SpecNode(n: JSONObject, state: SpecState) {{
    val kind = n.optString("kind", "stack")
    val id = n.optString("id", "")
    val label = n.optString("label", "")
    val a11y = n.optString("a11yLabel", label)
    val enabled = Predicates.evaluate(n.opt("enabledWhen"), state)
    val tag = Modifier.testTag(id)

    when (kind) {{
        "heading", "text" -> Text(label, modifier = tag)

        "banner" -> Text(
            label,
            color = if (n.optString("tone") == "error") MaterialTheme.colorScheme.error
                    else MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = tag.semantics {{ contentDescription = a11y }}
        )

        // `label =` is what gives this control an accessible name on Android.
        // A separate Text composable would not associate.
        "field" -> OutlinedTextField(
            value = (state.resolve(n.optString("bind")) as? String) ?: "",
            onValueChange = {{ state.values[n.optString("bind")] = it }},
            label = {{ Text(label) }},
            enabled = enabled,
            modifier = tag.semantics {{ contentDescription = a11y }}
        )

        "toggle" -> Row(verticalAlignment = androidx.compose.ui.Alignment.CenterVertically) {{
            Switch(
                checked = (state.resolve(n.optString("bind")) as? Boolean) ?: false,
                onCheckedChange = {{ state.values[n.optString("bind")] = it }},
                enabled = enabled,
                modifier = tag.semantics {{ contentDescription = a11y }}
            )
            Spacer(Modifier.width(8.dp)); Text(label)
        }}

        "button" -> Button(
            onClick = {{ Actions.apply(n.opt("action"), state) }},
            enabled = enabled,
            modifier = tag
        ) {{ Text(label) }}

        "list" -> {{
            val rows = state.collections[n.optString("of")] ?: mutableListOf()
            Column(modifier = tag) {{
                rows.forEach {{ r ->
                    ListItem(headlineContent = {{
                        Text((r["title"] ?: r["name"] ?: "").toString())
                    }})
                }}
            }}
        }}

        "divider" -> HorizontalDivider(modifier = tag)

        else -> Column(modifier = tag) {{
            val kids = n.optJSONArray("children") ?: return@Column
            (0 until kids.length()).forEach {{ i -> SpecNode(kids.getJSONObject(i), state) }}
        }}
    }}
}}

object Predicates {{
    fun looseEq(a: Any?, b: Any?): Boolean {{
        if (a is Boolean || b is Boolean) return a == b
        if (a is Number && b is Number) return Math.abs(a.toDouble() - b.toDouble()) < 1e-9
        if (a is String && b is String) return a.trim() == b.trim()
        return a == b
    }}

    fun evaluate(p: Any?, s: SpecState): Boolean {{
        if (p == null || p !is JSONObject) return true
        val op = p.optString("op")
        
        if (op == "and" || op == "or") {{
            val clauses = p.optJSONArray("clauses") ?: return true
            for (i in 0 until clauses.length()) {{
                val res = evaluate(clauses.optJSONObject(i), s)
                if (op == "and" && !res) return false
                if (op == "or" && res) return true
            }}
            return op == "and"
        }}
        if (op == "not") {{
            val clauses = p.optJSONArray("clauses")
            return if (clauses != null && clauses.length() > 0) !evaluate(clauses.optJSONObject(0), s) else true
        }}

        val left = s.resolve(p.optString("left"))
        val right = if (p.has("right")) p.get("right") else null

        return when (op) {{
            "truthy" -> left != null && left != false && left != 0 && left != ""
            "falsy" -> !(left != null && left != false && left != 0 && left != "")
            "nonempty" -> {{
                when (left) {{
                    is Collection<*> -> left.isNotEmpty()
                    is String -> left.isNotEmpty()
                    is JSONArray -> left.length() > 0
                    is JSONObject -> left.length() > 0
                    else -> left != null && left != false && left != 0
                }}
            }}
            "matches" -> {{
                if (left != null && right != null) {{
                    Regex(right.toString()).containsMatchIn(left.toString())
                }} else false
            }}
            "eq" -> looseEq(left, right)
            "ne" -> !looseEq(left, right)
            "gt", "lt", "gte", "lte" -> {{
                if (left == null || right == null) return false
                val aNum = left.toString().toDoubleOrNull()
                val bNum = right.toString().toDoubleOrNull()
                if (aNum != null && bNum != null) {{
                    when (op) {{
                        "gt" -> aNum > bNum
                        "lt" -> aNum < bNum
                        "gte" -> aNum >= bNum
                        "lte" -> aNum <= bNum
                        else -> false
                    }}
                }} else {{
                    val aStr = left.toString()
                    val bStr = right.toString()
                    when (op) {{
                        "gt" -> aStr > bStr
                        "lt" -> aStr < bStr
                        "gte" -> aStr >= bStr
                        "lte" -> aStr <= bStr
                        else -> false
                    }}
                }}
            }}
            else -> false
        }}
    }}
}}

object Actions {{
    fun expand(value: Any?, state: SpecState, row: Map<String, Any?>?, payload: Any?): Any? {{
        if (value is String) {{
            if (value == "$payload") return payload
            if (value.startsWith("$state.")) return state.resolve(value.substring(7))
            if (value.startsWith("$row.")) return row?.get(value.substring(5))
        }}
        if (value is JSONArray) {{
            val arr = JSONArray()
            for (i in 0 until value.length()) {{
                arr.put(expand(value.get(i), state, row, payload))
            }}
            return arr
        }}
        if (value is JSONObject) {{
            val obj = JSONObject()
            value.keys().forEach {{ k ->
                obj.put(k, expand(value.get(k), state, row, payload))
            }}
            return obj
        }}
        return value
    }}

    private fun rowMatches(row: Map<String, Any?>, match: JSONObject?): Boolean {{
        if (match == null) return true
        for (k in match.keys()) {{
            if (!Predicates.looseEq(row[k], match.get(k))) return false
        }}
        return true
    }}

    fun applyAction(action: JSONObject?, state: SpecState, payload: Any?, row: Map<String, Any?>?) {{
        if (action == null) return
        if (!Predicates.evaluate(action.optJSONObject("guardWhen"), state)) return
        val op = action.optString("op")
        val target = action.optString("target")

        when (op) {{
            "navigate" -> state.route = target
            "set" -> {{
                var v = if (action.has("value")) action.get("value") else payload
                if (action.has("from")) v = state.resolve(action.optString("from"))
                val expanded = expand(v, state, row, payload)
                val parts = target.split(".")
                if (parts.size == 1) {{
                    state.values[target] = expanded
                }} else {{
                    var cur: Any? = state.values[parts[0]] ?: state.collections[parts[0]]
                    for (i in 1 until parts.size - 1) {{
                        cur = when (cur) {{
                            is MutableMap<*, *> -> (cur as MutableMap<String, Any?>)[parts[i]]
                            is JSONObject -> cur.opt(parts[i])
                            else -> null
                        }}
                    }}
                    if (cur is MutableMap<*, *>) {{
                        (cur as MutableMap<String, Any?>)[parts.last()] = expanded
                    }}
                }}
            }}
            "clear" -> {{
                val decl = SPEC.optJSONObject("state")?.optJSONObject(target)
                val def = if (decl?.has("default") == true) decl.get("default") else when (decl?.optString("type")) {{
                    "string" -> ""; "number" -> 0; "boolean" -> false; else -> null
                }}
                state.values[target] = def
            }}
            "append" -> {{
                var newRow = expand(action.opt("value"), state, row, payload)
                if (newRow == JSONObject.NULL || newRow == null) newRow = payload
                if (newRow is JSONObject) {{
                    val map = mutableMapOf<String, Any?>()
                    newRow.keys().forEach {{ k -> map[k] = newRow.get(k) }}
                    state.collections.getOrPut(target) {{ mutableListOf() }}.add(map)
                }}
            }}
            "remove" -> {{
                val matchVal = expand(action.opt("value"), state, row, payload)
                val match = matchVal as? JSONObject ?: payload as? JSONObject
                state.collections[target]?.removeAll {{ r -> rowMatches(r, match) }}
            }}
            "update" -> {{
                val specPayloadVal = expand(action.opt("value"), state, row, payload)
                val specPayload = specPayloadVal as? JSONObject ?: payload as? JSONObject ?: JSONObject()
                val where = specPayload.optJSONObject("where")
                val setChanges = specPayload.optJSONObject("set")
                state.collections[target]?.forEach {{ r ->
                    if (rowMatches(r, where)) {{
                        setChanges?.keys()?.forEach {{ k -> r[k] = setChanges.get(k) }}
                    }}
                }}
            }}
            "submit", "dismiss" -> if (target.isNotEmpty()) state.values[target] = op == "submit"
        }}
    }}

    fun apply(a: Any?, state: SpecState, payload: Any? = null, row: Map<String, Any?>? = null) {{
        if (a is JSONArray) {{
            for (i in 0 until a.length()) {{
                applyAction(a.optJSONObject(i), state, payload, row)
            }}
        }} else if (a is JSONObject) {{
            applyAction(a, state, payload, row)
        }}
    }}
}}

// Serves /state /facts /tree /actions /invoke /reset on port {port}.
object Instrumentation {{
    fun start(state: SpecState) {{
        Thread {{
            val server = java.net.ServerSocket({port})
            while (true) {{
                try {{
                    val client = server.accept()
                    val reader = client.inputStream.bufferedReader()
                    val requestLine = reader.readLine() ?: continue
                    val parts = requestLine.split(" ")
                    if (parts.size < 2) {{ client.close(); continue }}
                    
                    val path = parts[1]
                    var contentLength = 0
                    while (true) {{
                        val line = reader.readLine()
                        if (line.isNullOrEmpty()) break
                        if (line.lowercase().startsWith("content-length:")) {{
                            contentLength = line.substringAfter(":").trim().toIntOrNull() ?: 0
                        }}
                    }}
                    
                    var body = ""
                    if (contentLength > 0) {{
                        val chars = CharArray(contentLength)
                        reader.read(chars, 0, contentLength)
                        body = String(chars)
                    }}

                    var responseJson = "{{}}"
                    android.os.Handler(android.os.Looper.getMainLooper()).post {{
                        try {{
                            responseJson = handle(path, body, state)
                        }} catch (e: Exception) {{
                            responseJson = JSONObject().put("error", e.message).toString()
                        }}
                        val response = "HTTP/1.1 200 OK\\r\\nContent-Type: application/json\\r\\nConnection: close\\r\\n\\r\\n$responseJson"
                        client.outputStream.write(response.toByteArray())
                        client.close()
                    }}
                }} catch (e: Exception) {{
                    e.printStackTrace()
                }}
            }}
        }}.start()
    }}

    private fun handle(path: String, body: String, state: SpecState): String {{
        return when (path) {{
            "/state" -> {{
                val obj = JSONObject()
                obj.put("route", state.route)
                val colls = JSONObject()
                state.collections.forEach {{ (k, v) ->
                    val arr = JSONArray()
                    v.forEach {{ r -> arr.put(JSONObject(r)) }}
                    colls.put(k, arr)
                }}
                obj.put("collections", colls)
                state.values.forEach {{ (k, v) -> obj.put(k, v) }}
                obj.toString()
            }}
            "/facts" -> {{
                val proj = project(state)
                val nodes = mutableListOf<JSONObject>()
                walk(proj, nodes)
                
                val facts = JSONObject()
                facts.put("error_visible", nodes.any {{ it.optString("kind") == "banner" && it.optString("tone") == "error" }})
                facts.put("empty_state_visible", nodes.any {{ it.optString("kind") == "banner" && it.optString("tone") == "empty" }})
                
                val enabled = JSONObject()
                val fieldValues = JSONObject()
                val options = JSONObject()
                val visibleRows = JSONObject()
                
                nodes.forEach {{ n ->
                    val id = n.optString("id", "")
                    if (id.isNotEmpty()) {{
                        if (n.optBoolean("focusable")) enabled.put(id, n.optBoolean("enabled"))
                        if (n.optString("kind") == "field" || n.optString("kind") == "select") fieldValues.put(id, n.opt("value"))
                        val opts = n.optJSONArray("options")
                        if (opts != null && opts.length() > 0) options.put(id, opts)
                    }}
                    if (n.optString("kind") == "list") {{
                        val rows = n.optJSONArray("rows")?.length() ?: 0
                        if (id.isNotEmpty()) visibleRows.put(id, rows)
                        val of = n.optString("of", "")
                        if (of.isNotEmpty()) visibleRows.put(of, rows)
                    }}
                }}
                facts.put("enabled", enabled)
                facts.put("field_values", fieldValues)
                facts.put("options", options)
                facts.put("visible_rows", visibleRows)
                facts.toString()
            }}
            "/tree" -> {{
                val proj = project(state)
                fun toTree(n: JSONObject): JSONObject {{
                    val kind = n.optString("kind")
                    val canonicalKind = when (kind) {{
                        "text", "heading" -> "text"
                        "field" -> "input"
                        "select" -> "choice"
                        "toggle" -> "boolean"
                        "button" -> "action"
                        "list" -> "collection"
                        "listItem" -> "item"
                        "divider" -> "separator"
                        "banner" -> "status"
                        else -> "container"
                    }}
                    val treeNode = JSONObject()
                    treeNode.put("kind", canonicalKind)
                    treeNode.put("name", n.optString("a11y").takeIf {{ it.isNotEmpty() }} ?: n.optString("label").takeIf {{ it.isNotEmpty() }} ?: JSONObject.NULL)
                    treeNode.put("node_id", n.optString("id").takeIf {{ it.isNotEmpty() }} ?: JSONObject.NULL)
                    treeNode.put("focusable", n.optBoolean("focusable"))
                    
                    val children = JSONArray()
                    val kids = n.optJSONArray("children")
                    if (kids != null) {{
                        for (i in 0 until kids.length()) {{
                            children.put(toTree(kids.getJSONObject(i)))
                        }}
                    }}
                    treeNode.put("children", children)
                    return treeNode
                }}
                toTree(proj).toString()
            }}
            "/actions" -> {{
                val proj = project(state)
                val nodes = mutableListOf<JSONObject>()
                walk(proj, nodes)
                val out = JSONArray()
                nodes.forEach {{ n ->
                    if (n.optBoolean("focusable") && n.optString("id").isNotEmpty()) {{
                        val act = JSONObject()
                        act.put("id", n.optString("id"))
                        act.put("kind", n.optString("kind"))
                        act.put("name", n.optString("a11y").takeIf {{ it.isNotEmpty() }} ?: n.optString("label"))
                        act.put("enabled", n.optBoolean("enabled"))
                        act.put("value", n.opt("value") ?: JSONObject.NULL)
                        act.put("options", n.optJSONArray("options") ?: JSONArray())
                        out.put(act)
                    }}
                    if (n.optString("kind") == "list" && n.has("rowAction") && n.optString("id").isNotEmpty()) {{
                        val rows = n.optJSONArray("rows") ?: JSONArray()
                        val rowLabel = n.optString("rowLabel", "")
                        for (i in 0 until rows.length()) {{
                            val r = rows.getJSONObject(i)
                            val act = JSONObject()
                            act.put("id", n.optString("id") + "#" + i)
                            act.put("kind", "listItem")
                            val name = if (rowLabel.isNotEmpty()) r.optString(rowLabel) else ""
                            act.put("name", name.takeIf {{ it.isNotEmpty() }} ?: JSONObject.NULL)
                            act.put("enabled", n.optBoolean("enabled"))
                            act.put("value", JSONObject.NULL)
                            act.put("options", JSONArray())
                            out.put(act)
                        }}
                    }}
                }}
                out.toString()
            }}
            "/invoke" -> {{
                val json = JSONObject(body)
                val id = json.optString("id")
                val value = if (json.has("value")) json.get("value") else null
                
                val proj = project(state)
                val nodes = mutableListOf<JSONObject>()
                walk(proj, nodes)
                
                if (id.contains("#")) {{
                    val (listId, idxStr) = id.split("#")
                    val lst = nodes.find {{ it.optString("id") == listId && it.optString("kind") == "list" }}
                    if (lst != null && lst.has("rowAction") && lst.optBoolean("enabled")) {{
                        val rowMap = mutableMapOf<String, Any?>()
                        val r = lst.optJSONArray("rows")?.optJSONObject(idxStr.toInt())
                        r?.keys()?.forEach {{ k -> rowMap[k] = r.get(k) }}
                        Actions.apply(lst.opt("rowAction"), state, value, rowMap)
                    }}
                }} else {{
                    val node = nodes.find {{ it.optString("id") == id }}
                    if (node != null && node.optBoolean("enabled")) {{
                        val kind = node.optString("kind")
                        val bind = node.optString("bind")
                        if ((kind == "field" || kind == "select") && bind.isNotEmpty()) {{
                            state.values[bind] = value
                        }} else if (kind == "toggle" && bind.isNotEmpty()) {{
                            state.values[bind] = if (value == null) !(node.optBoolean("value")) else value as Boolean
                        }}
                        Actions.apply(node.opt("action"), state, value, null)
                    }}
                }}
                """{{"status":"ok"}}"""
            }}
            "/reset" -> {{
                state.reset()
                """{{"status":"ok"}}"""
            }}
            else -> "{{}}"
        }}
    }}

    private fun project(state: SpecState): JSONObject {{
        val screens = SPEC.optJSONArray("screens") ?: JSONArray()
        var screen = screens.optJSONObject(0)
        for (i in 0 until screens.length()) {{
            if (screens.getJSONObject(i).optString("id") == state.route) {{
                screen = screens.getJSONObject(i)
                break
            }}
        }}
        if (screen == null) return JSONObject()
        
        fun conv(n: JSONObject): JSONObject? {{
            if (!Predicates.evaluate(n.opt("visibleWhen"), state)) return null
            val bind = n.optString("bind", "")
            val declared = SPEC.optJSONObject("state")?.optJSONObject(bind)
            
            val p = JSONObject()
            p.put("kind", n.optString("kind", "stack"))
            p.put("id", n.optString("id", ""))
            p.put("label", n.optString("label", ""))
            p.put("a11y", n.optString("a11yLabel", n.optString("label", "")))
            p.put("tone", n.optString("tone", ""))
            p.put("enabled", Predicates.evaluate(n.opt("enabledWhen"), state))
            val focusable = setOf("field", "select", "toggle", "button").contains(p.optString("kind"))
            p.put("focusable", focusable)
            p.put("bind", bind)
            p.put("value", if (bind.isNotEmpty()) state.resolve(bind) else JSONObject.NULL)
            p.put("options", declared?.optJSONArray("options") ?: JSONArray())
            
            val of = n.optString("of", "")
            if (p.optString("kind") == "list" && of.isNotEmpty()) {{
                val arr = JSONArray()
                state.collections[of]?.forEach {{ arr.put(JSONObject(it)) }}
                p.put("rows", arr)
                p.put("of", of)
            }}
            if (n.has("action")) p.put("action", n.opt("action"))
            if (n.has("rowAction")) p.put("rowAction", n.opt("rowAction"))
            if (n.has("rowLabel")) p.put("rowLabel", n.optString("rowLabel"))
            
            val kids = JSONArray()
            n.optJSONArray("children")?.let {{ c ->
                for (i in 0 until c.length()) {{
                    conv(c.getJSONObject(i))?.let {{ kids.put(it) }}
                }}
            }}
            p.put("children", kids)
            return p
        }}
        
        val root = JSONObject()
        root.put("kind", "screen")
        root.put("id", screen.optString("id"))
        root.put("label", screen.optString("title", SPEC.optString("title")))
        root.put("a11y", root.optString("label"))
        root.put("enabled", true)
        root.put("focusable", false)
        val children = JSONArray()
        screen.optJSONArray("children")?.let {{ c ->
            for (i in 0 until c.length()) {{
                conv(c.getJSONObject(i))?.let {{ children.put(it) }}
            }}
        }}
        root.put("children", children)
        return root
    }}

    private fun walk(n: JSONObject, out: MutableList<JSONObject>) {{
        out.add(n)
        val kids = n.optJSONArray("children")
        if (kids != null) {{
            for (i in 0 until kids.length()) {{
                walk(kids.getJSONObject(i), out)
            }}
        }}
    }}
}}

class MainActivity : ComponentActivity() {{
    override fun onCreate(savedInstanceState: Bundle?) {{
        super.onCreate(savedInstanceState)
        val state = SpecState()
        Instrumentation.start(state)
        setContent {{{{
            MaterialTheme {{{{
                val screens = SPEC.optJSONArray("screens")!!
                val entry = SPEC.optString("entry")
                var screen = screens.getJSONObject(0)
                for (i in 0 until screens.length()) {{{{
                    if (screens.getJSONObject(i).optString("id") == entry) {{{{
                        screen = screens.getJSONObject(i)
                    }}}}
                }}}}
                val kids = screen.optJSONArray("children")
                val list = (0 until (kids?.length() ?: 0)).map {{{{ kids!!.getJSONObject(it) }}}}
                SpecNodes(list, state)
            }}}}
        }}}}
    }}}}
}}}}
'''


class ComposeRenderer:
    host = "compose"
    profile = COMPOSE

    def emit(self, spec: dict) -> dict[str, str]:
        return {
            "MainActivity.kt": APP_KT.format(
                spec_json=json.dumps(spec, indent=2),
                port=DEFAULT_PORTS["compose"],
            )
        }

    def open(self, spec: dict):
        return ComposeSession()


class ComposeSession(HttpBridgeSession):
    def __init__(self, port: int | None = None):
        super().__init__("compose", port)


class SimulatedComposeSession(SimulatedSession):
    """Pipeline-only stand-in. See session.assert_measurable."""

    def __init__(self, spec: dict):
        super().__init__(spec, COMPOSE)
