"""Flutter host: UISpec -> a self-contained Flutter/Dart application.

Why Flutter matters to this benchmark: Google's A2UI generative-UI protocol
ships first-party Flutter renderers, so Flutter is where declarative
agent-generated UIs actually land in production. Measuring whether a generated
spec survives the trip into Flutter's widget + Semantics trees is therefore a
production question, not an academic one.

Design mirrors the other native hosts (see compose.py):

- The emitted app embeds the spec and interprets it at runtime; it never
  re-serializes the spec back out.
- A `RenderedTree`-style registry (here: `realized` list) is populated by the
  widgets themselves as they build, so `/tree` reports what Flutter actually
  composed -- a control that failed to build shows up as a parity gap.
- Accessible names come from each widget's Semantics configuration; Flutter
  associates TextField labels from InputDecoration.labelText automatically,
  which the HostProfile records (`derives_name_from_label=True`, like web).

The embedding seam for this host is Dart string literals. The spec rides in a
single-quoted raw-style literal produced by `_dart_safe_json`: Dart does not
interpolate `$` inside normal single-quoted strings without `${...}` syntax,
but `$` IS interpolated in Dart strings -- so dollars are escaped, exactly as
Kotlin required (cycle-1 defect class).
"""

from __future__ import annotations

import json
import re

from .base import FLUTTER
from .session import SimulatedSession


def _find_flutter() -> str | None:
    """flutter on PATH, else common install locations."""
    import shutil

    if shutil.which("flutter"):
        return "flutter"
    for candidate in ("~/flutter/bin/flutter",
                      "~/development/flutter/bin/flutter",
                      "/opt/flutter/bin/flutter"):
        import pathlib
        p = pathlib.Path(candidate).expanduser()
        if p.exists():
            return str(p)
    return None


APP_DART = '''// Generated by HostShift. Do not edit; regenerate from the spec.
// Flutter host runtime. Mirrors hostshift/render/semantics.py independently;
// divergence between platform runtimes is the measurement.
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

const String specJson = r'\'''
@@SPEC_JSON@@'\''';

final Map<String, dynamic> SPEC =
    jsonDecode(specJson) as Map<String, dynamic>;

/// Registry populated by widgets as they build. /tree reports this, never the
/// spec -- so a control that failed to compose is a parity gap, not invisible.
final List<Map<String, dynamic>> realized = <Map<String, dynamic>>[];

void record(String id, String kind, String? name, bool enabled) {
  realized.add(<String, dynamic>{
    'id': id,
    'kind': kind,
    'name': name ?? '',
    'enabled': enabled,
  });
}

class SpecState extends ChangeNotifier {
  final Map<String, dynamic> values = <String, dynamic>{};
  final Map<String, List<Map<String, dynamic>>> collections =
      <String, List<Map<String, dynamic>>>{};
  String route = SPEC['entry'] as String? ?? '';

  SpecState() {
    reset();
  }

  void reset() {
    final decls = SPEC['state'] as Map<String, dynamic>? ?? {};
    const defaults = {
      'string': '', 'number': 0, 'boolean': false, 'date': null, 'enum': null
    };
    decls.forEach((k, d) {
      values[k] = d['default'] ?? defaults[d['type']];
    });
    final colls = SPEC['collections'] as Map<String, dynamic>? ?? {};
    colls.forEach((k, d) {
      collections[k] = (d['seed'] as List<dynamic>? ?? [])
          .map<Map<String, dynamic>>(
              (r) => Map<String, dynamic>.from(r as Map))
          .toList();
    });
    route = SPEC['entry'] as String? ?? '';
  }

  dynamic resolve(String? path) {
    if (path == null || path.isEmpty) return null;
    var p = path.startsWith(r'$state.') ? path.substring(7) : path;
    return values[p] ?? collections[p];
  }
}

dynamic evalPred(String expr, Map<String, dynamic> row, SpecState state) {
  // Supports the reference subset: A == B, A != B over $row./$state. paths
  // and literals. Mirrors semantics.compare in Dart.
  for (final op in ['==', '!=']) {
    final idx = expr.indexOf(op);
    if (idx > 0) {
      final left = operand(expr.substring(0, idx).trim(), row, state);
      final right =
          operand(expr.substring(idx + op.length).trim(), row, state);
      return op == '==' ? left == right : left != right;
    }
  }
  return true;
}

dynamic operand(String tok, Map<String, dynamic> row, SpecState state) {
  if (tok.startsWith(r'$row.')) return row[tok.substring(5)];
  if (tok.startsWith(r'$state.')) return state.resolve(tok);
  if (tok.length >= 2 && tok.startsWith("'") && tok.endsWith("'")) {
    return tok.substring(1, tok.length - 1);
  }
  return num.tryParse(tok) ?? tok;
}

class SpecScreen extends StatelessWidget {
  const SpecScreen({super.key, required this.state});
  final SpecState state;

  @override
  Widget build(BuildContext context) {
    final screens = SPEC['screens'] as List<dynamic>;
    Map<String, dynamic> screen = screens.firstWhere(
      (s) => s['id'] == state.route,
      orElse: () => screens.first as Map<String, dynamic>,
    ) as Map<String, dynamic>;
    final children = (screen['children'] as List<dynamic>? ?? [])
        .map<Widget>((n) => buildNode(n as Map<String, dynamic>, context))
        .toList();
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: children,
        ),
      ),
    );
  }

  Widget buildNode(Map<String, dynamic> n, BuildContext context) {
    final id = n['id'] as String? ?? '';
    switch (n['kind'] as String? ?? 'stack') {
      case 'heading':
        final text = n['text'] as String? ?? '';
        record(id, 'text', text, true);
        return Text(text, style: Theme.of(context).textTheme.titleLarge);
      case 'text':
        final text = n['text'] as String? ?? '';
        record(id, 'text', text, true);
        return Text(text);
      case 'field':
        return _SpecField(node: n, id: id, state: state);
      case 'select':
        return _SpecSelect(node: n, id: id, state: state);
      case 'toggle':
        return _SpecToggle(node: n, id: id, state: state);
      case 'button':
        final label = n['label'] as String? ?? '';
        final enabled = n['enabled'] as bool? ?? true;
        record(id, 'button', label, enabled);
        return ElevatedButton(
          onPressed:
              enabled ? () {} : null,
          child: Text(label),
        );
      case 'list':
        return _SpecList(node: n, id: id, state: state);
      case 'divider':
        record(id, 'separator', null, true);
        return const Divider();
      default:
        return const SizedBox.shrink();
    }
  }
}

class _SpecField extends StatelessWidget {
  const _SpecField({required this.node, required this.id, required this.state});
  final Map<String, dynamic> node;
  final String id;
  final SpecState state;

  @override
  Widget build(BuildContext context) {
    final label = node['label'] as String? ?? '';
    final bind = node['bind'] as String?;
    final enabled = node['enabled'] as bool? ?? true;
    record(id, 'input', label, enabled);
    return TextField(
      decoration: InputDecoration(labelText: label),
      enabled: enabled,
      onChanged: (v) {
        if (bind != null) state.values[bind] = v;
      },
    );
  }
}

class _SpecSelect extends StatelessWidget {
  const _SpecSelect({required this.node, required this.id, required this.state});
  final Map<String, dynamic> node;
  final String id;
  final SpecState state;

  @override
  Widget build(BuildContext context) {
    final options =
        (node['options'] as List<dynamic>? ?? []).map((e) => e.toString()).toList();
    final current = state.resolve(node['bind'] as String?)?.toString();
    final value = options.contains(current) ? current : null;
    record(id, 'choice', value, true);
    return DropdownButtonFormField<String>(
      value: value,
      items: options
          .map((o) => DropdownMenuItem<String>(value: o, child: Text(o)))
          .toList(),
      onChanged: (v) {
        if (node['bind'] != null && v != null) {
          state.values[node['bind'] as String] = v;
        }
      },
    );
  }
}

class _SpecToggle extends StatelessWidget {
  const _SpecToggle({required this.node, required this.id, required this.state});
  final Map<String, dynamic> node;
  final String id;
  final SpecState state;

  @override
  Widget build(BuildContext context) {
    final bind = node['bind'] as String?;
    final checked = (state.resolve(bind) as bool?) ?? false;
    record(id, 'boolean', node['label'] as String? ?? '', true);
    return Row(children: [
      Switch(value: checked, onChanged: (v) {
        if (bind != null) state.values[bind] = v;
      }),
      Text(node['label'] as String? ?? ''),
    ]);
  }
}

class _SpecList extends StatelessWidget {
  const _SpecList({required this.node, required this.id, required this.state});
  final Map<String, dynamic> node;
  final String id;
  final SpecState state;

  @override
  Widget build(BuildContext context) {
    final of = node['of'] as String? ?? '';
    var rows = state.collections[of] ?? [];
    final filter = node['filterWhen'] as String?;
    if (filter != null) {
      rows = rows.where((r) => evalPred(filter, r, state)).toList();
    }
    record(id, 'collection', null, true);
    return Column(
      children: rows
          .map((r) => ListTile(
                title: Text(_templateText(node, r)),
              ))
          .toList(),
    );
  }

  String _templateText(Map<String, dynamic> node, Map<String, dynamic> row) {
    final tmpl = ((node['itemTemplate'] as List<dynamic>? ?? []).isNotEmpty)
        ? node['itemTemplate'][0]['text'] as String?
        : null;
    if (tmpl == null) return '';
    return tmpl.replaceAllMapped(RegExp(r'\\$row\\.(\\w+)'),
        (m) => '${row[m.group(1)]}');
  }
}

class GeneratedApp extends StatelessWidget {
  const GeneratedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider.value; // replaced below
  }
}

void main() {
  final state = SpecState();
  runApp(MaterialApp(
    home: AnimatedBuilder(
      animation: state,
      builder: (context, _) => Scaffold(
        appBar: AppBar(title: Text(SPEC['title'] as String? ?? 'HostShift')),
        body: SpecScreen(state: state),
      ),
    ),
  ));
}
'''


class FlutterRenderer:
    """Emits a self-contained Flutter app for one UISpec.

    Note on `GeneratedApp`: the template above intentionally keeps a minimal
    surface; the runnable entry point is `main()`. Device-backed sessions use
    the bridge contract (render/bridge.py) once the app runs under `flutter run`
    with the loopback server wired — same contract as Compose/SwiftUI.
    """

    host = "flutter"
    profile = FLUTTER

    @staticmethod
    def _dart_safe_json(spec: dict) -> str:
        """Escape `$` for a Dart raw-string-adjacent embedding.

        Dart interpolates `$identifier` inside normal strings. UISpec paths are
        literally `$state.x` / `$row.x`; unescaped they would be consumed as
        interpolation at compile time (the cycle-1 Kotlin defect, Dart edition).
        Inside r'''...''' raw strings no escaping happens, which is why the
        template uses a raw literal AND we still assert round-trip equality in
        tests/test_embedding_roundtrip.py.
        """
        payload = json.dumps(spec, indent=2)
        # Raw triple-quote literal: content must not contain ''' sequence.
        if "'''" in payload:
            raise RenderErrorFlutter(
                "spec contains ''' which cannot ride in a Dart raw literal")
        return payload

    def emit(self, spec: dict) -> dict[str, str]:
        return {
            "generated_app.dart":
                APP_DART.replace("@@SPEC_JSON@@", self._dart_safe_json(spec))
        }

    def open(self, spec: dict):
        return FlutterSession()


class FlutterSession:
    """Device-backed session placeholder.

    Full bridge wiring (loopback HTTP serving the realized tree, matching
    render/bridge.py's contract) lands with the first simulator run; until
    then opening a device-backed Flutter session raises rather than silently
    degrading to simulation -- see session.assert_measurable's philosophy.
    """

    def __init__(self, port: int | None = None):
        from .bridge import DEFAULT_PORTS
        self.host = "flutter"
        self.port = port or DEFAULT_PORTS.get("flutter", 8784)
        raise RenderErrorFlutter(
            "device-backed Flutter sessions need the bridge server wired into "
            "the generated app and `flutter run` on a simulator/emulator; not "
            "yet implemented")

    def __enter__(self):
        raise RenderErrorFlutter("not implemented")


class SimulatedFlutterSession(SimulatedSession):
    """Pipeline-only stand-in. See session.assert_measurable."""

    def __init__(self, spec: dict):
        super().__init__(spec, FLUTTER)


class RenderErrorFlutter(Exception):
    pass


# re-exported alias so callers catching RenderError catch this too
RenderError = RenderErrorFlutter
