"""iOS host: UISpec -> a SwiftUI application.

The generated app embeds the spec, interprets it at runtime, and serves the
instrumentation contract over loopback so the harness can read realized state.

The tree endpoint walks the SwiftUI accessibility hierarchy rather than the
spec, which is the only way render parity can catch a control that was built but
never exposed -- a distinction that matters on this platform, where a view can
be perfectly visible and still absent from the accessibility tree.
"""

from __future__ import annotations

import json

from .base import SWIFTUI
from .bridge import DEFAULT_PORTS, HttpBridgeSession
from .session import SimulatedSession

APP_SWIFT = '''// Generated by HostShift. Do not edit; regenerate from the spec.
import SwiftUI
import Network

let specJSON = #"""
{spec_json}
"""#

let SPEC: [String: Any] = try! JSONSerialization.jsonObject(
    with: Data(specJSON.utf8)) as! [String: Any]

// MARK: - Runtime state

final class SpecState: ObservableObject {{
    @Published var values: [String: Any] = [:]
    @Published var collections: [String: [[String: Any]]] = [:]
    @Published var route: String = SPEC["entry"] as? String ?? ""

    init() {{ reset() }}

    func reset() {{
        values = [:]
        collections = [:]
        if let decls = SPEC["state"] as? [String: [String: Any]] {{
            for (k, d) in decls {{ values[k] = d["default"] ?? defaultFor(d["type"] as? String) }}
        }}
        if let colls = SPEC["collections"] as? [String: [String: Any]] {{
            for (k, d) in colls {{ collections[k] = d["seed"] as? [[String: Any]] ?? [] }}
        }}
        route = SPEC["entry"] as? String ?? ""
    }}

    private func defaultFor(_ t: String?) -> Any? {{
        switch t {{
        case "string": return ""
        case "number": return 0
        case "boolean": return false
        default: return nil
        }}
    }}

    func resolve(_ path: String?) -> Any? {{
        guard let path else {{ return nil }}
        if let direct = values[path] {{ return direct }}
        return collections[path]
    }}

    func set(_ path: String, _ v: Any?) {{ values[path] = v }}
}}

// MARK: - View construction

struct SpecView: View {{
    @EnvironmentObject var state: SpecState
    let nodes: [[String: Any]]

    var body: some View {{
        VStack(alignment: .leading, spacing: 12) {{
            ForEach(0..<nodes.count, id: \\.self) {{ i in build(nodes[i]) }}
        }}
        .padding()
    }}

    @ViewBuilder
    func build(_ n: [String: Any]) -> some View {{
        let kind = n["kind"] as? String ?? "stack"
        let id = n["id"] as? String
        let label = n["label"] as? String ?? ""
        let a11y = n["a11yLabel"] as? String ?? label
        let enabled = Predicate.evaluate(n["enabledWhen"], state)

        switch kind {{
        case "heading", "text":
            Text(label).accessibilityIdentifier(id ?? "").accessibilityLabel(a11y)
        case "banner":
            Text(label)
                .foregroundColor((n["tone"] as? String) == "error" ? .red : .secondary)
                .accessibilityIdentifier(id ?? "")
                .accessibilityAddTraits((n["tone"] as? String) == "error" ? .isStaticText : [])
        case "field":
            // The placeholder becomes the accessibility label on this platform,
            // so a visible label alone does name the control.
            TextField(label, text: Binding(
                get: {{ state.resolve(n["bind"] as? String) as? String ?? "" }},
                set: {{ if let b = n["bind"] as? String {{ state.set(b, $0) }} }}))
                .disabled(!enabled)
                .accessibilityIdentifier(id ?? "")
                .accessibilityLabel(a11y)
        case "toggle":
            Toggle(label, isOn: Binding(
                get: {{ state.resolve(n["bind"] as? String) as? Bool ?? false }},
                set: {{ if let b = n["bind"] as? String {{ state.set(b, $0) }} }}))
                .disabled(!enabled)
                .accessibilityIdentifier(id ?? "")
        case "button":
            Button(label) {{ Actions.apply(n["action"], state) }}
                .disabled(!enabled)
                .accessibilityIdentifier(id ?? "")
        case "select":
            // A choice control: the picker carries the accessible name; on
            // this platform the placeholder/label names it implicitly.
            Picker(a11y, selection: Binding(
                get: {{ state.resolve(n["bind"] as? String) as? String ?? "" }},
                set: {{ if let b = n["bind"] as? String {{ state.set(b, $0) }} }})) {{
                let decls = SPEC["state"] as? [String: [String: Any]] ?? [:]
                let opts = (decls[n["bind"] as? String ?? ""]?["options"] as? [String]) ?? []
                ForEach(0..<opts.count, id: \\.self) {{ i in Text(opts[i]).tag(opts[i]) }}
            }}
            .pickerStyle(.inline)
            .disabled(!enabled)
            .accessibilityIdentifier(id ?? "")
            .accessibilityLabel(a11y)
        case "list":
            let of = n["of"] as? String ?? ""
            let rows = state.collections[of] ?? []
            let rowAction = n["rowAction"]
            let rowLabel = n["rowLabel"] as? String ?? ""
            VStack(alignment: .leading, spacing: 4) {{
                ForEach(0..<rows.count, id: \\.self) {{ i in
                    let r = rows[i]
                    if rowAction != nil {{
                        Button((r[rowLabel] ?? r["title"] ?? r["name"] ?? "") as? String ?? "") {{
                            Actions.apply(rowAction, state, payload: nil, row: r)
                        }}
                        .disabled(enabled == false)
                        .accessibilityIdentifier((id ?? "") + "#\\(i)")
                    }} else {{
                        Text((r["title"] as? String) ?? (r["name"] as? String) ?? "")
                    }}
                }}
            }}
        case "divider":
            Divider()
        case "image":
            Image(systemName: "photo").accessibilityLabel(a11y)
        default:
            SpecView(nodes: n["children"] as? [[String: Any]] ?? [])
        }}
    }}
}}


// Predicate and Actions mirror hostshift/render/semantics.py. They are a
// separate implementation on purpose: divergence between per-platform runtimes
// is what this benchmark measures.
enum Predicate {{
    static func evaluate(_ p: Any?, _ s: SpecState) -> Bool {{
        guard let p = p as? [String: Any], let op = p["op"] as? String else {{ return true }}
        if op == "and" {{ return (p["clauses"] as? [[String: Any]] ?? []).allSatisfy {{ evaluate($0, s) }} }}
        if op == "or" {{ return (p["clauses"] as? [[String: Any]] ?? []).contains {{ evaluate($0, s) }} }}
        if op == "not" {{ return !evaluate((p["clauses"] as? [[String: Any]] ?? []).first, s) }}
        let left = s.resolve(p["left"] as? String)
        let right = p["right"]
        switch op {{
        case "truthy": return isTruthy(left)
        case "falsy": return !isTruthy(left)
        case "nonempty": return isNonEmpty(left)
        case "matches":
            if let l = left as? String, let r = right as? String {{ return l.range(of: r, options: .regularExpression) != nil }}
            return false
        case "eq": return looseEq(left, right)
        case "ne": return !looseEq(left, right)
        case "gt", "lt", "gte", "lte":
            if left == nil || right == nil {{ return false }}
            if let a = asDouble(left), let b = asDouble(right) {{
                if op == "gt" {{ return a > b }} else if op == "lt" {{ return a < b }} else if op == "gte" {{ return a >= b }} else {{ return a <= b }}
            }}
            let aStr = String(describing: left), bStr = String(describing: right)
            if op == "gt" {{ return aStr > bStr }} else if op == "lt" {{ return aStr < bStr }} else if op == "gte" {{ return aStr >= bStr }} else {{ return aStr <= bStr }}
        default: return false
        }}
    }}
    static func isTruthy(_ v: Any?) -> Bool {{
        if let v = v as? Bool {{ return v }}
        if let v = v as? String {{ return !v.isEmpty }}
        if let v = v as? Int {{ return v != 0 }}
        if let v = v as? Double {{ return v != 0.0 }}
        if let v = v as? [Any] {{ return !v.isEmpty }}
        if let v = v as? [String: Any] {{ return !v.isEmpty }}
        return v != nil
    }}
    static func isNonEmpty(_ v: Any?) -> Bool {{
        if let v = v as? String {{ return !v.isEmpty }}
        if let v = v as? [Any] {{ return !v.isEmpty }}
        if let v = v as? [String: Any] {{ return !v.isEmpty }}
        return isTruthy(v)
    }}
    static func looseEq(_ a: Any?, _ b: Any?) -> Bool {{
        if let a = a as? Bool, let b = b as? Bool {{ return a == b }}
        if let a = asDouble(a), let b = asDouble(b) {{ return abs(a - b) < 1e-9 }}
        if let a = a as? String, let b = b as? String {{ return a.trimmingCharacters(in: .whitespacesAndNewlines) == b.trimmingCharacters(in: .whitespacesAndNewlines) }}
        if a == nil && b == nil {{ return true }}
        if a == nil || b == nil {{ return false }}
        return String(describing: a) == String(describing: b)
    }}
    static func asDouble(_ v: Any?) -> Double? {{
        if let v = v as? Double {{ return v }}
        if let v = v as? Int {{ return Double(v) }}
        if let v = v as? String {{ return Double(v) }}
        return nil
    }}
}}
enum Actions {{
    static func apply(_ a: Any?, _ s: SpecState, payload: Any? = nil, row: [String: Any]? = nil) {{
        if a == nil {{ return }}
        for act in (a as? [Any] ?? [a!]) {{
            if let actDict = act as? [String: Any] {{ applySingle(actDict, s, payload: payload, row: row) }}
        }}
    }}
    static func applySingle(_ action: [String: Any], _ s: SpecState, payload: Any?, row: [String: Any]?) {{
        if !Predicate.evaluate(action["guardWhen"], s) {{ return }}
        let op = action["op"] as? String ?? "", target = action["target"] as? String ?? ""
        switch op {{
        case "navigate": s.route = target
        case "set":
            var value = action.keys.contains("value") ? action["value"] : payload
            if let from = action["from"] as? String {{ value = s.resolve(from) }}
            s.set(target, expand(value, s, row: row, payload: payload))
        case "clear":
            if let decls = SPEC["state"] as? [String: Any], let d = decls[target] as? [String: Any] {{
                s.set(target, d["default"] ?? defaultFor(d["type"] as? String))
            }} else {{ s.set(target, nil) }}
        case "append":
            var rows = s.collections[target] ?? []
            if let nr = (expand(action["value"], s, row: row, payload: payload) ?? payload) as? [String: Any] {{
                rows.append(nr); s.collections[target] = rows
            }}
        case "remove":
            let match = (expand(action["value"], s, row: row, payload: payload) as? [String: Any]) ?? (payload as? [String: Any]) ?? [:]
            var rows = s.collections[target] ?? []
            rows.removeAll {{ rowMatches($0, match) }}
            s.collections[target] = rows
        case "update":
            let match = (expand(action["value"], s, row: row, payload: payload) as? [String: Any]) ?? (payload as? [String: Any]) ?? [:]
            let whereClause = match["where"] as? [String: Any] ?? [:], setClause = match["set"] as? [String: Any] ?? [:]
            var rows = s.collections[target] ?? []
            for i in 0..<rows.count {{
                if rowMatches(rows[i], whereClause) {{ for (k, v) in setClause {{ rows[i][k] = v }} }}
            }}
            s.collections[target] = rows
        case "submit": if !target.isEmpty {{ s.set(target, true) }}
        case "dismiss": if !target.isEmpty {{ s.set(target, false) }}
        default: break
        }}
    }}
    static func expand(_ value: Any?, _ s: SpecState, row: [String: Any]?, payload: Any?) -> Any? {{
        if let vStr = value as? String {{
            if vStr == "$payload" {{ return payload }}
            if vStr.hasPrefix("$state.") {{ return s.resolve(String(vStr.dropFirst(7))) }}
            if vStr.hasPrefix("$row.") {{ return row?[String(vStr.dropFirst(5))] }}
            return value
        }}
        if let arr = value as? [Any] {{ return arr.map {{ expand($0, s, row: row, payload: payload) }} }}
        if let dict = value as? [String: Any] {{
            var res = [String: Any](); for (k, v) in dict {{ res[k] = expand(v, s, row: row, payload: payload) }}; return res
        }}
        return value
    }}
    static func rowMatches(_ row: [String: Any], _ match: [String: Any]) -> Bool {{
        for (k, v) in match {{ if !Predicate.looseEq(row[k], v) {{ return false }} }}
        return true
    }}
    static func defaultFor(_ t: String?) -> Any? {{
        switch t {{ case "string": return ""; case "number": return 0; case "boolean": return false; default: return nil }}
    }}
}}

// MARK: - Instrumentation
// Serves /state /facts /tree /actions /invoke /reset on port {port}.
// `tree` must walk the realized accessibility hierarchy, not the spec.
enum Instrumentation {{
    static var listener: NWListener?
    static func start(_ state: SpecState) {{
        do {{
            let port = NWEndpoint.Port(rawValue: {port})!
            listener = try NWListener(using: .tcp, on: port)
            listener?.newConnectionHandler = {{ connection in
                connection.start(queue: .global())
                receiveNextMessage(on: connection, state: state)
            }}
            listener?.start(queue: .global())
        }} catch {{ print("Failed to start listener: \\(error)") }}
    }}
    static func receiveNextMessage(on connection: NWConnection, state: SpecState) {{
        connection.receive(minimumIncompleteLength: 1, maximumLength: 65536) {{ data, _, isComplete, error in
            if let data = data, !data.isEmpty {{
                let reqStr = String(decoding: data, as: UTF8.self)
                handleRequest(reqStr, data: data, connection: connection, state: state)
            }}
            if isComplete || error != nil {{ connection.cancel() }} else {{ receiveNextMessage(on: connection, state: state) }}
        }}
    }}
    static func handleRequest(_ request: String, data: Data, connection: NWConnection, state: SpecState) {{
        let lines = request.components(separatedBy: "\\r\\n")
        guard let first = lines.first else {{ return }}
        let parts = first.split(separator: " ")
        guard parts.count >= 2 else {{ return }}
        let method = parts[0], path = parts[1]
        var responseBody: Data? = nil
        let group = DispatchGroup()
        group.enter()
        DispatchQueue.main.async {{
            if method == "GET" && path == "/state" {{
                let dict: [String: Any] = ["values": state.values, "collections": state.collections, "route": state.route]
                responseBody = try? JSONSerialization.data(withJSONObject: dict)
            }} else if method == "GET" && path == "/facts" {{
                responseBody = try? JSONSerialization.data(withJSONObject: computeFacts(state))
            }} else if method == "GET" && path == "/actions" {{
                responseBody = try? JSONSerialization.data(withJSONObject: computeActions(state))
            }} else if method == "GET" && path == "/tree" {{
                responseBody = try? JSONSerialization.data(withJSONObject: getTree(state))
            }} else if method == "POST" && path == "/invoke" {{
                handleInvoke(request, state: state)
                responseBody = "{{}}".data(using: .utf8)
            }} else if method == "POST" && path == "/reset" {{
                state.reset()
                responseBody = "{{}}".data(using: .utf8)
            }}
            group.leave()
        }}
        group.wait()
        let body = responseBody ?? Data()
        let header = "HTTP/1.1 200 OK\\r\\nContent-Type: application/json\\r\\nContent-Length: \\(body.count)\\r\\n\\r\\n"
        let resp = (header.data(using: .utf8) ?? Data()) + body
        connection.send(content: resp, completion: .contentProcessed({{ _ in connection.cancel() }}))
    }}
    
    static func project(_ state: SpecState) -> [String: Any] {{
        let screens = SPEC["screens"] as? [[String: Any]] ?? []
        let route = state.route.isEmpty ? (SPEC["entry"] as? String) : state.route
        guard let screen = screens.first(where: {{ ($0["id"] as? String) == route }}) else {{ return [:] }}
        func conv(_ node: [String: Any]) -> [String: Any]? {{
            if !Predicate.evaluate(node["visibleWhen"], state) {{ return nil }}
            let kind = node["kind"] as? String ?? "stack"
            let bind = node["bind"] as? String
            var options: [String] = []
            if let b = bind, let decls = SPEC["state"] as? [String: Any], let decl = decls[b] as? [String: Any] {{ options = decl["options"] as? [String] ?? [] }}
            var pn: [String: Any] = [
                "kind": kind,
                "id": node["id"] as Any,
                "label": node["label"] as Any,
                "a11y": (node["a11yLabel"] as? String) ?? (node["label"] as? String) as Any,
                "tone": node["tone"] as Any,
                "enabled": Predicate.evaluate(node["enabledWhen"], state),
                "focusable": ["field", "select", "toggle", "button"].contains(kind),
                "bind": bind as Any,
                "value": (bind != nil ? state.resolve(bind!) : nil) ?? NSNull(),
                "options": options,
                "action": node["action"] as Any,
                "rawNode": node
            ]
            if kind == "list", let of = node["of"] as? String {{ pn["rows"] = state.collections[of] ?? [] }}
            var kids = [[String: Any]]()
            if let children = node["children"] as? [[String: Any]] {{
                for k in children {{ if let c = conv(k) {{ kids.append(c) }} }}
            }}
            pn["children"] = kids
            return pn
        }}
        var root: [String: Any] = [
            "kind": "screen", "id": screen["id"] as Any,
            "enabled": true, "focusable": false, "children": []
        ]
        var kids = [[String: Any]]()
        if let children = screen["children"] as? [[String: Any]] {{
            for k in children {{ if let c = conv(k) {{ kids.append(c) }} }}
        }}
        root["children"] = kids
        return root
    }}
    static func walkProjected(_ node: [String: Any]) -> [[String: Any]] {{
        var res = [node]
        if let kids = node["children"] as? [[String: Any]] {{ for k in kids {{ res.append(contentsOf: walkProjected(k)) }} }}
        return res
    }}
    static func computeFacts(_ state: SpecState) -> [String: Any] {{
        let root = project(state)
        let nodes = walkProjected(root)
        var error_visible = false, empty_state_visible = false
        var enabled = [String: Bool](), field_values = [String: Any](), optionsDict = [String: [String]](), visible_rows = [String: Int]()
        for n in nodes {{
            if n["kind"] as? String == "banner" {{
                if n["tone"] as? String == "error" {{ error_visible = true }}
                if n["tone"] as? String == "empty" {{ empty_state_visible = true }}
            }}
            if let id = n["id"] as? String {{
                if n["focusable"] as? Bool == true {{ enabled[id] = n["enabled"] as? Bool ?? false }}
                if let k = n["kind"] as? String, (k == "field" || k == "select") {{ field_values[id] = n["value"] ?? NSNull() }}
                if let opts = n["options"] as? [String], !opts.isEmpty {{ optionsDict[id] = opts }}
            }}
            if n["kind"] as? String == "list" {{ visible_rows[(n["id"] as? String) ?? "rows"] = (n["rows"] as? [[String: Any]])?.count ?? 0 }}
        }}
        func walkSpecForLists(_ specNode: [String: Any]) {{
            if specNode["kind"] as? String == "list", let of = specNode["of"] as? String {{
                if let pNode = nodes.first(where: {{ $0["kind"] as? String == "list" && ($0["id"] as? String) == (specNode["id"] as? String) }}) {{
                    visible_rows[of] = (pNode["rows"] as? [[String: Any]])?.count ?? 0
                }}
            }}
            if let kids = specNode["children"] as? [[String: Any]] {{ for k in kids {{ walkSpecForLists(k) }} }}
        }}
        if let screens = SPEC["screens"] as? [[String: Any]] {{ for s in screens {{ if let kids = s["children"] as? [[String: Any]] {{ for k in kids {{ walkSpecForLists(k) }} }} }} }}
        return ["error_visible": error_visible, "empty_state_visible": empty_state_visible, "enabled": enabled, "field_values": field_values, "options": optionsDict, "visible_rows": visible_rows]
    }}
    static func computeActions(_ state: SpecState) -> [[String: Any]] {{
        // Same contract as every other host (render/base.py Session.actions):
        // {{id, kind, name, enabled, value, options}} -- keeping the operator's
        // view identical across hosts is what makes an interaction-parity gap
        // attributable to the interface rather than to the operator.
        let root = project(state)
        var actionsList = [[String: Any]]()
        for n in walkProjected(root) {{
            if n["focusable"] as? Bool == true, let id = n["id"] as? String, !id.isEmpty {{
                actionsList.append([
                    "id": id,
                    "kind": n["kind"] as? String ?? "",
                    "name": (n["a11y"] as? String) ?? (n["label"] as? String) ?? NSNull(),
                    "enabled": n["enabled"] as? Bool ?? false,
                    "value": n["value"] ?? NSNull(),
                    "options": n["options"] as? [String] ?? [],
                ])
            }}
            if n["kind"] as? String == "list", n["rowAction"] != nil,
               let id = n["id"] as? String, !id.isEmpty {{
                let rows = n["rows"] as? [[String: Any]] ?? []
                let rowLabel = n["rowLabel"] as? String ?? ""
                for (i, r) in rows.enumerated() {{
                    let name = rowLabel.isEmpty ? "" : ((r[rowLabel] as? String) ?? "")
                    actionsList.append([
                        "id": id + "#\\(i)",
                        "kind": "listItem",
                        "name": name.isEmpty ? NSNull() : name,
                        "enabled": n["enabled"] as? Bool ?? false,
                        "value": NSNull(),
                        "options": [String](),
                    ])
                }}
            }}
        }}
        return actionsList
    }}
    static func getTree(_ state: SpecState) -> [String: Any] {{
        var root: [String: Any] = ["kind": "screen", "name": NSNull(), "node_id": NSNull(), "focusable": false, "children": []]
        if let scene = UIApplication.shared.connectedScenes.first as? UIWindowScene, let window = scene.windows.first {{
            root = walkUIView(window, state: state)
        }} else if let window = UIApplication.shared.windows.first {{
            root = walkUIView(window, state: state)
        }}
        return root
    }}
    static func walkUIView(_ element: Any, state: SpecState) -> [String: Any] {{
        var node: [String: Any] = ["kind": "container", "name": NSNull(), "node_id": NSNull(), "focusable": false, "children": []]
        var children = [[String: Any]]()
        if let nsObject = element as? NSObject {{
            let id = nsObject.accessibilityIdentifier
            node["name"] = nsObject.accessibilityLabel ?? NSNull()
            node["node_id"] = id ?? NSNull()
            var focusable = false, kind = "container"
            let traits = nsObject.accessibilityTraits
            if traits.contains(.button) {{ kind = "button"; focusable = true }}
            else if traits.contains(.searchField) || (element as? UIView)?.description.contains("TextField") == true {{ kind = "field"; focusable = true }}
            else if traits.contains(.staticText) {{ kind = "text" }}
            if let idStr = id, idStr != "", let n = walkProjected(project(state)).first(where: {{ ($0["id"] as? String) == idStr }}) {{
                kind = n["kind"] as? String ?? kind; focusable = n["focusable"] as? Bool ?? focusable
            }} else if nsObject.isAccessibilityElement {{ focusable = true }}
            node["kind"] = kind; node["focusable"] = focusable
            if let view = element as? UIView {{
                if let a11yElements = view.accessibilityElements {{ for el in a11yElements {{ children.append(walkUIView(el, state: state)) }} }}
                else {{ for sub in view.subviews {{ children.append(walkUIView(sub, state: state)) }} }}
            }} else if let elements = nsObject.accessibilityElements {{
                for el in elements {{ children.append(walkUIView(el, state: state)) }}
            }}
        }}
        node["children"] = children
        return node
    }}
    static func handleInvoke(_ request: String, state: SpecState) {{
        if let bodyStart = request.components(separatedBy: "\\r\\n\\r\\n").last,
           let data = bodyStart.data(using: .utf8),
           let req = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let id = req["id"] as? String {{
            let value = req["value"]
            if let n = walkProjected(project(state)).first(where: {{ ($0["id"] as? String) == id }}), n["enabled"] as? Bool == true && n["focusable"] as? Bool == true {{
                if let bind = n["bind"] as? String, !(value is NSNull) {{ state.set(bind, value) }}
                Actions.apply(n["action"], state, payload: value, row: nil)
            }}
        }}
    }}
}}


@main
struct GeneratedApp: App {{
    @StateObject private var state = SpecState()
    var body: some Scene {{
        WindowGroup {{
            RootView()
                .environmentObject(state)
                .onAppear {{ Instrumentation.start(state) }}
        }}
    }}
}}

// Reads state.route, so an action that navigates actually swaps the screen.
// The earlier revision rendered only the entry screen, which made every
// multi-screen task structurally unwinnable on this host.
struct RootView: View {{
    @EnvironmentObject var state: SpecState

    var body: some View {{
        let screens = SPEC["screens"] as? [[String: Any]] ?? []
        let route = state.route.isEmpty ? (SPEC["entry"] as? String ?? "") : state.route
        let screen = screens.first {{ ($0["id"] as? String) == route }} ?? screens.first
        let children = screen?["children"] as? [[String: Any]] ?? []
        return SpecView(nodes: children)
            .padding()
    }}
}}
'''


class SwiftUIRenderer:
    host = "swiftui"
    profile = SWIFTUI

    def emit(self, spec: dict) -> dict[str, str]:
        return {
            "GeneratedApp.swift": APP_SWIFT.format(
                spec_json=json.dumps(spec, indent=2),
                port=DEFAULT_PORTS["swiftui"],
            )
        }

    def open(self, spec: dict):
        return SwiftUISession()


class SwiftUISession(HttpBridgeSession):
    def __init__(self, port: int | None = None):
        super().__init__("swiftui", port)


class SimulatedSwiftUISession(SimulatedSession):
    """Pipeline-only stand-in. See session.assert_measurable."""

    def __init__(self, spec: dict):
        super().__init__(spec, SWIFTUI)
