"""Terminal host: UISpec -> a Textual application.

The terminal is in the host set precisely because it is awkward. It has no
raster surface, no pointer, and in most toolkits no assistive-technology
channel at all. Constructs that every graphical host takes for granted have to
degrade, and a portability metric that never encounters a host like this would
flatter every runtime it scores.

Its inclusion is also the strongest test of whether a declarative spec is really
host-independent or merely framework-independent-within-the-GUI-family.
"""

from __future__ import annotations

import json

from ..widgettree import Widget
from .base import RenderError, TUI
from .session import SimulatedSession

APP_PY = '''"""Generated by HostShift. Terminal realization of a UISpec."""
import json, sys
from textual.app import App, ComposeResult
from textual.containers import Vertical, Horizontal
from textual.widgets import (
    Static, Label, Input, Select, Checkbox, Button, ListView, ListItem, Rule,
)

SPEC = json.loads(r"""{spec_json}""")

DEFAULTS = {{"string": "", "number": 0, "boolean": False, "date": None, "enum": None}}
FOCUSABLE = {{"field", "select", "toggle", "button"}}


def assign(obj, path, value):
    parts = path.split(".")
    cur = obj
    for p in parts[:-1]:
        if not isinstance(cur.get(p), dict):
            cur[p] = {{}}
        cur = cur[p]
    cur[parts[-1]] = value


def resolve(state, path):
    if not path:
        return None
    if path.endswith(".length"):
        b = resolve(state, path[:-7])
        return len(b) if hasattr(b, "__len__") else None
    cur = state
    for p in path.split("."):
        if isinstance(cur, dict) and p in cur:
            cur = cur[p]
        elif isinstance(cur, dict) and p in cur.get("collections", {{}}):
            cur = cur["collections"][p]
        else:
            return None
    return cur


def loose_eq(a, b):
    if isinstance(a, bool) or isinstance(b, bool):
        return a == b
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return abs(float(a) - float(b)) < 1e-9
    if isinstance(a, str) and isinstance(b, str):
        return a.strip() == b.strip()
    return a == b


def evaluate(pred, state):
    if not pred:
        return True
    op = pred.get("op")
    if op == "and":
        return all(evaluate(c, state) for c in pred.get("clauses", []))
    if op == "or":
        return any(evaluate(c, state) for c in pred.get("clauses", []))
    if op == "not":
        return not evaluate(pred.get("clauses", [None])[0], state)
    left, right = resolve(state, pred.get("left")), pred.get("right")
    if op == "truthy":
        return bool(left)
    if op == "falsy":
        return not bool(left)
    if op == "nonempty":
        return bool(left) and (len(left) > 0 if hasattr(left, "__len__") else True)
    if op == "eq":
        return loose_eq(left, right)
    if op == "ne":
        return not loose_eq(left, right)
    if op in ("gt", "lt", "gte", "lte"):
        if left is None or right is None:
            return False
        try:
            a, b = float(left), float(right)
        except (TypeError, ValueError):
            a, b = str(left), str(right)
        return {{"gt": a > b, "lt": a < b, "gte": a >= b, "lte": a <= b}}[op]
    return False


class GeneratedApp(App):
    CSS = "Screen {{ padding: 1 2; }}"

    def __init__(self):
        super().__init__()
        self.state = {{"collections": {{}}, "route": SPEC.get("entry")}}
        for k, d in (SPEC.get("state") or {{}}).items():
            assign(self.state, k, d.get("default", DEFAULTS.get(d.get("type"))))
        for k, d in (SPEC.get("collections") or {{}}).items():
            self.state["collections"][k] = list(d.get("seed") or [])

    def current_screen(self):
        route = self.state.get("route") or SPEC.get("entry")
        for s in SPEC.get("screens", []):
            if s.get("id") == route:
                return s
        raise RuntimeError("route matches no screen")

    def compose(self) -> ComposeResult:
        yield from self._compose_nodes(self.current_screen().get("children", []))

    def _compose_nodes(self, nodes):
        for n in nodes:
            if not evaluate(n.get("visibleWhen"), self.state):
                continue
            yield from self._compose_one(n)

    def _compose_one(self, n):
        kind = n.get("kind")
        nid = n.get("id")
        label = n.get("label") or ""
        enabled = evaluate(n.get("enabledWhen"), self.state)
        if kind in ("text", "heading"):
            yield Static(label, id=nid)
        elif kind == "divider":
            yield Rule(id=nid)
        elif kind == "banner":
            yield Static(label, id=nid, classes="tone-" + (n.get("tone") or "info"))
        elif kind == "image":
            # No raster surface. The degradation is deliberate and visible in
            # the parity numbers rather than hidden behind a blank widget.
            yield Static("[image: " + (n.get("a11yLabel") or label) + "]", id=nid)
        elif kind == "field":
            yield Input(value=str(resolve(self.state, n.get("bind")) or ""),
                        placeholder=label, id=nid, disabled=not enabled)
        elif kind == "select":
            opts = ((SPEC.get("state") or {{}}).get(n.get("bind") or "", {{}}).get("options") or [])
            yield Select([(o, o) for o in opts], id=nid, disabled=not enabled)
        elif kind == "toggle":
            yield Checkbox(label, value=bool(resolve(self.state, n.get("bind"))),
                           id=nid, disabled=not enabled)
        elif kind == "button":
            yield Button(label, id=nid, disabled=not enabled)
        elif kind == "list":
            rows = self.state["collections"].get(n.get("of"), [])
            yield ListView(*[ListItem(Label(str(r.get("title") or r.get("name") or "")))
                             for r in rows], id=nid)
        else:
            container = Horizontal if n.get("axis") == "horizontal" else Vertical
            yield container(*self._collect(n.get("children") or []), id=nid)

    def _collect(self, nodes):
        return list(self._compose_nodes(nodes))


if __name__ == "__main__":
    GeneratedApp().run()
'''


class TuiRenderer:
    host = "tui"

    def emit(self, spec: dict) -> dict[str, str]:
        return {"app.py": APP_PY.format(spec_json=json.dumps(spec))}

    def open(self, spec: dict):
        try:
            return TuiSession(spec)
        except ImportError as exc:
            raise RenderError("the terminal host needs Textual: pip install textual") from exc


class TuiSession:
    """Device-backed: runs the generated Textual app and reads its live tree.

    Textual drives an async event loop, so the session runs it on a worker
    thread and marshals calls across. That indirection is unfortunate but
    unavoidable if the session API is to stay synchronous and identical to the
    other hosts -- and keeping the API identical is what makes cross-host
    numbers comparable.
    """

    simulated = False
    host = "tui"

    def __init__(self, spec: dict):
        import textual  # noqa: F401,PLC0415
        import asyncio
        import threading
        import copy
        import json

        loc = {}
        exec(APP_PY.format(spec_json=json.dumps(spec)), loc)
        self._app = loc["GeneratedApp"]()

        self._loop = asyncio.new_event_loop()
        self._ready = threading.Event()
        self._pilot = None

        self._thread = threading.Thread(target=self._run_app, daemon=True)
        self._thread.start()
        self._ready.wait()

    def _run_app(self):
        import asyncio
        asyncio.set_event_loop(self._loop)

        async def run():
            async with self._app.run_test() as pilot:
                self._pilot = pilot
                self._stop_event = asyncio.Event()
                self._ready.set()
                await self._stop_event.wait()

        self._loop.run_until_complete(run())

    def _run_coro(self, coro):
        import asyncio
        future = asyncio.run_coroutine_threadsafe(coro, self._loop)
        return future.result()

    def widget_tree(self) -> Widget:
        return self._run_coro(self._get_widget_tree())

    async def _get_widget_tree(self) -> Widget:
        return widget_from_textual(self._app.screen)

    def state(self) -> dict:
        return self._run_coro(self._get_state())

    async def _get_state(self) -> dict:
        import copy
        return copy.deepcopy(self._app.state)

    def ui_facts(self) -> dict:
        return self._run_coro(self._get_ui_facts())

    async def _get_ui_facts(self) -> dict:
        f = {
            "error_visible": False,
            "empty_state_visible": False,
            "enabled": {},
            "field_values": {},
            "options": {},
            "visible_rows": {},
        }
        for w in [self._app.screen] + list(self._app.screen.walk_children()):
            nid = getattr(w, "id", None)
            cls = type(w).__name__

            if cls == "Static" and w.has_class("tone-error"):
                f["error_visible"] = True
            if cls == "Static" and w.has_class("tone-empty"):
                f["empty_state_visible"] = True

            if nid:
                if cls in ("Input", "Select", "Checkbox", "Button"):
                    f["enabled"][nid] = not getattr(w, "disabled", False)

                if cls in ("Input", "Select"):
                    val = getattr(w, "value", None)
                    if cls == "Select" and not isinstance(val, (str, int, float, bool)) and val is not None:
                        val = None
                    f["field_values"][nid] = val

                if cls == "Select":
                    opts = getattr(w, "_options", [])
                    if opts and len(opts) > 0 and isinstance(opts[0], tuple):
                        f["options"][nid] = [o[1] for o in opts if o[1] is not None]

                if cls == "ListView":
                    f["visible_rows"][nid] = len(list(w.children))

        return f

    def actions(self) -> list[dict]:
        return self._run_coro(self._get_actions())

    async def _get_actions(self) -> list[dict]:
        out = []
        for w in list(self._app.screen.walk_children()):
            nid = getattr(w, "id", None)
            if not nid:
                continue
            cls = type(w).__name__
            kind = {
                "Input": "input", "Select": "choice",
                "Checkbox": "boolean", "Button": "action",
            }.get(cls)
            if kind:
                raw_name = getattr(w, "label", None) or getattr(w, "renderable", None)
                name = str(raw_name).strip() or None if raw_name is not None else None
                if kind == "input":
                    name = None

                val = getattr(w, "value", None)
                if cls == "Select" and not isinstance(val, (str, int, float, bool)) and val is not None:
                    val = None

                opts = []
                if cls == "Select":
                    _opts = getattr(w, "_options", [])
                    if _opts and len(_opts) > 0 and isinstance(_opts[0], tuple):
                        opts = [o[1] for o in _opts if o[1] is not None]

                out.append({
                    "id": nid,
                    "kind": kind,
                    "name": name,
                    "enabled": not getattr(w, "disabled", False),
                    "value": val,
                    "options": opts,
                })

            if cls == "ListView":
                for i, child in enumerate(w.children):
                    label_w = next(iter(child.children), None)
                    raw_label = getattr(label_w, "renderable", "") if label_w else ""
                    out.append({
                        "id": f"{nid}#{i}",
                        "kind": "listItem",
                        "name": str(raw_label).strip() or None,
                        "enabled": not getattr(w, "disabled", False),
                        "value": None,
                        "options": [],
                    })
        return out

    def invoke(self, node_id: str, value: object | None = None) -> None:
        self._run_coro(self._invoke(node_id, value))

    async def _invoke(self, node_id: str, value: object | None) -> None:
        if "#" in node_id:
            list_id, _, idx_str = node_id.partition("#")
            idx = int(idx_str)
            try:
                lst = self._app.query_one(f"#{list_id}")
            except Exception:
                return

            items = list(lst.children)
            if 0 <= idx < len(items):
                item = items[idx]
                if not getattr(item, "id", None):
                    item.id = f"{list_id}_item_{idx}"
                await self._pilot.click(f"#{item.id}")
        else:
            try:
                w = self._app.query_one(f"#{node_id}")
            except Exception:
                return

            cls = type(w).__name__
            if cls == "Input":
                if value is not None:
                    w.value = str(value)
            elif cls == "Select":
                if value is not None:
                    w.value = value
            elif cls == "Checkbox":
                if value is not None:
                    w.value = bool(value)
                else:
                    await self._pilot.click(f"#{node_id}")
            elif cls == "Button":
                await self._pilot.click(f"#{node_id}")

    def close(self) -> None:
        if not hasattr(self, "_loop"):
            return
            
        def _stop():
            self._stop_event.set()
            
        try:
            self._loop.call_soon_threadsafe(_stop)
            self._thread.join(timeout=2.0)
        except Exception:
            pass


class SimulatedTuiSession(SimulatedSession):
    """Pipeline-only stand-in. See session.assert_measurable."""

    def __init__(self, spec: dict):
        super().__init__(spec, TUI)


def widget_from_textual(node) -> Widget:
    """Lower a live Textual widget hierarchy into the canonical tree.

    Kept here rather than inside the session so it can be unit tested against
    fixtures without spinning up an event loop.
    """
    from .base import TUI as _TUI  # noqa: PLC0415

    cls = type(node).__name__
    kind = {
        "Vertical": "container", "Horizontal": "container", "Screen": "container",
        "Static": "text", "Label": "text", "Input": "input", "Select": "choice",
        "Checkbox": "boolean", "Button": "action", "ListView": "collection",
        "ListItem": "item", "Rule": "separator",
    }.get(cls, "container")

    # A terminal toolkit exposes no accessible-name channel. Whatever text is
    # visible is all an assistive technology could ever get, and for controls
    # rendered without inline text that is nothing.
    name = None
    if kind in ("text", "action", "boolean", "item"):
        raw = getattr(node, "label", None) or getattr(node, "renderable", None)
        name = str(raw).strip() or None if raw is not None else None
    if kind == "input" and not _TUI.derives_name_from_label:
        name = None

    return Widget(
        kind=kind,
        name=name,
        node_id=getattr(node, "id", None),
        focusable=kind in {"input", "choice", "boolean", "action"},
        children=[widget_from_textual(c) for c in getattr(node, "children", [])],
    )
